version: '3.5'
services:
  hub:
    build: .
    image: hub
    container_name: jupyterhub
    ports:
      - "8080:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- hub_data:/srv/jupyterhub
    networks:
      - jupyterhub 
    environment:
      DOCKER_NOTEBOOL_IMAGE: notebook-image #'d4n1el/tensorflow-2-notebook-gpu' 
      DOCKER_NOTEBOOK_DIR: '/home/user'

#volumes:
  #hub_data

networks: 
  jupyterhub:
    name: jupyterhub
