version: '3.5'

services:
  
  hub:
    build: .
    image: hub
    container_name: jupyterhub
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      #- hub_data:/srv/jupyterhub
    networks:
      - jupyterhub-network 
    environment:
      DOCKER_NOTEBOOL_IMAGE: notebook:tensorflow-v2-gpu 
      DOCKER_NOTEBOOK_DIR: '/home/user' 

  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    ports: 
      - 8000:8000
      - 9000:9000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


volumes:
  portainer_data:
  #hub_data:

networks: 
  jupyterhub-network:
    external: true
