#!/bin/bash

# need to create docker network image for jupyterhub
#docker network create jupyterhub
#docker build -t hub .

# also image for docker spawner
#docker pull d4n1el/tensorflow-2-notebook-gpu #jupyter/tensorflow-notebook'

docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock --net jupyterhub --name jupyterhub -p 8000:8000 hub
